<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HELLLO" failures="1" tests="4" name="com.automationFW.tests.LoginUser" time="92.133" errors="0" timestamp="2024-09-18T20:47:34 IST" skipped="0">
  <testcase classname="com.automationFW.tests.LoginUser" name="verifyUserIsNotAbletoLoginWithIncorrectEmailAndPass" time="21.288">
    <failure message=" expected [Your email or psassword is incorrect!] but found [Your email or password is incorrect!]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError:  expected [Your email or psassword is incorrect!] but found [Your email or password is incorrect!]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at com.automationFW.Utils.CommonAssertions.verifyEqual(CommonAssertions.java:10)
at com.automationFW.tests.LoginUser.lambda$0(LoginUser.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.automationFW.tests.LoginUser.verifyUserIsNotAbletoLoginWithIncorrectEmailAndPass(LoginUser.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyUserIsNotAbletoLoginWithIncorrectEmailAndPass -->
  <testcase classname="com.automationFW.tests.LoginUser" name="verifyUserIsAbletoSignupAndLoginWithValidEmailPass" time="34.083"/>
  <testcase classname="com.automationFW.tests.LoginUser" name="verifyUserIsNotAbletoRegisterWithExistingEMail" time="15.587"/>
  <testcase classname="com.automationFW.tests.LoginUser" name="verifyUserIsAbletoSignupAndLoginWithValidEmailPassAndDeleteAccount" time="21.175"/>
</testsuite> <!-- com.automationFW.tests.LoginUser -->
